### ISSUE TITLE
Metadata submission to external registry

### ISSUE THREAD

**Issue by graybeal** [metadatacenter-attic/cedar-features#22]
Submit CEDAR metadata to an external registry (e.g., a repository for metadata, or a repository for a specific entity, like an antibody registry).

**Comment by graybeal** [comment]
Submit CEDAR metadata to an external registry (e.g., a repository for metadata, or a repository for a specific entity, like an antibody registry).

**Comment by martinjoconnor** [comment]
First version of AIRR pipeline with NCBI, ImmPort, and LINCS  metadata submission  completed in September, 2017.
