### ISSUE TITLE
Basic Notification

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter-attic/cedar-features#60]
Notify users of resource sharing, being added to group, their templates/elements/fields being used etc.

https://github.com/search?utf8=%E2%9C%93&q=user%3Ametadatacenter+label:Notification&type=Issues

**Comment by graybeal** [comment]
Could include 'system going down in 5 minutes' (?)

**Comment by graybeal** [comment]
Could it be used to notify external systems (e.g., when an instance is saved or declared final) ?

**Comment by martinjoconnor** [comment]
Basic notification system released in 1.4.0.  Used primarily for submission notifications.

#77 will cover more advanced notification, and #78 will cover external notification.
